---
output:
  html_document:
    number_sections: no
    toc: no
---	

<br/><br/>

### CHEATSHEET

<br/>

##### STATISTICS

- [Correlations, evaluation metrics, variance...](STATISTICS_indices.html)

##### DIVERSITY indices

- [Abundance (Hill's numbers - *Leinster, Chao*)](DIVERSITY_measures_abundance.html)
- [Functional (FD, Gower's distance, clustering)](DIVERSITY_measures_functional.html)
- [Phylogenetic (PD - *Faith, Chao*)](DIVERSITY_measures_phylogenetic.html)
- [Partitioning (alpha, beta - *Whittaker, Baselga, Jost*)](DIVERSITY_measures_partitioning.html)
- [Communities (CWM, SNC, 4th corner)](DIVERSITY_measures_communities.html)
- [Richness (undetected, shared, richness - *Chao*)](DIVERSITY_measures_richness.html)

##### TRAITS

- [Imputation (methods comparison)](DIVERSITY_traits_imputation.html)

##### MODELS

- [Null models]()
- [Meta-analysis](MODELS_meta_analysis.html)


<br/><br/>

### CODE / PROGRAMMING

<br/>

#### [`LaTeX`](https://www.latex-project.org/)

<div style="text-align:center;">
<embed src="documents/COURS_latex_beamer.pdf" width='900' height='700' allowfullscreen webkitallowfullscreen></embed>
</div>

<br/><br/>

### LOGICIEL R

<br/>

#### [`ggplot2`](https://ggplot2.tidyverse.org/)

<div style="text-align:center;">
<embed src="documents/COURS_ggplot2_COMPLETE.pdf" width='900' height='700' allowfullscreen webkitallowfullscreen></embed>
</div>
